---
- name: Deploying our application
  ansible.builtin.include_tasks: 1-deploy_web_app.yml

- name: Wiping all stuff
  ansible.builtin.import_tasks: 0-wipe.yml
  when: web_app_full_wipe | bool
  tags: [wipe]