global:
  scrape_interval: "5s"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090
        - promtail:9080
  - job_name: grafana
    static_configs:
      - targets:
        - grafana:3000
  - job_name: loki
    static_configs:
      - targets:
        - loki:3100
  - job_name: web_apps
    static_configs:
      - targets:
        - python_app:5000
        - js_app:8080