scrape_configs:
  - job_name: "docker"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "docker"
          __path__: "/var/lib/docker/containers/*/*-json.log"
    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            container_name: attrs.container
      - labels:
          container: container_name
