- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Add current user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
