- name: Secure Docker Configuration - Disable Root Access
  become: true
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "no-new-privileges": true,
        "userns-remap": "default"
      }
    owner: root
    group: root
    mode: '0644'
  notify: Restart Docker
